[package]
name = "bpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
csv = "1.1.6"
rayon = "1.6.1"
serde = {version="1.0.151", features = ["derive"]}
